[package]
name = "drawning"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

raster = "0.2.0"
rand = "0.8.3"
